### ISSUE TITLE
Help SKY plugin

### ISSUE THREAD

**Issue by milan4566** [oscar-broman/SKY#12]
I have one problem, please help.

I need SKY.so plugin. I download https://github.com/oscar-broman/SKY but no .so plugin

My server work in linux and need SKY.so not SKY.dll

please compile to .so file and send link

I need it for weapon config https://github.com/oscar-broman/samp-weapon-config

works great on windows with SKY.dll

Thanks..

**Comment by Jeroen52** [comment]
What Linux distro are you using?

**Comment by milan4566** [comment]
Debian 6.0 x86 on the machine VPS

**Comment by Jeroen52** [comment]
I recommend you to upgrade your distro to 8.0 as 6.0 is already EOL.

More information here: https://wiki.debian.org/DebianSqueeze

**Comment by milan4566** [comment]
In my personal PC is windows, but my VPS use debian 6.0 x86. 
I need .so  not .dll

**Comment by Jeroen52** [comment]
I am aware, however I recommend you to upgrade to Debian 8.0 as Debian 6.0 is EOL and won't receive security updates.

**Comment by Jeroen52** [comment]
I don't think that you get how important it is for you to upgrade immediately.

Debian 6.0 does no longer receive any updates, it is out of Long Term Support. It has reached the End of Life. And it has been in End of Life since February 29th 2016.
Nearly 11 months without any (security) updates.
Here is a list of security updates, which you have missed most of them if not all. [2017](https://www.debian.org/security/2017/) [2016](https://www.debian.org/security/2016/)

Your main priority shouldn't be that .so file, it should be to upgrade away from 6.0 to something more up-to-date like 7.0 or 8.0.

Regardless, here is your SKY.so file, compiled on Debian Squeeze.
https://mirror.jeroendeneef.com/samp/SKY/unstable/3e322cf8db2a749ae08fa21bf24eedf982133fc3/Linux/debian/6.0/SKY.so

If you'd like to compike it yourself, do the following.

```sh
sudo apt-get update
sudo apt-get upgrade
sudo apt-get git build-essential
git clone https://github.com/oscar-broman/SKY.git
cd SKY
make SKY
```
Now you should have your SKY.so built.

A note: This should only be done on 32-bit architectures to make sure that it builds correctly.

**Comment by milan4566** [comment]
Why my server is unable to read plugin SKY.so
My server log.. http://pastebin.com/6Zsy7PxP
My server cfg.. http://pastebin.com/D0WdaVAc
My include.. http://pastebin.com/88ANeLRZ

I added SKY.inc and weapon-config.inc in folder /pawno/include/, and added SKY.so in folder plugins in my vps.

where real mistake? someone to help?

**Comment by Jeroen52** [comment]
Is that all the server log states?

And put the weapon-config include at the bottom of the list of includes,
and SKY above that..
Recompile and test it again.

**Comment by milan4566** [comment]
the same is happening, I can not believe
I put everything and go restart server will not start


all the same in server_log.txt
