### ISSUE TITLE
Packet was modified..

### ISSUE THREAD

**Issue by realhus** [oscar-broman/SKY#43]
Hello.
After i started using SKY i started getting packet was modied by... msgs in the logs. Then suddenly everyone timesout.
Im using the last version!

**Comment by ADRFranklin** [comment]
That doesn't have any thing to do with SKY, packet modified is fine, it just means the client send half a packet or they experienced packet loss and didn't send the full packet.

In the rare cases it means the player might be trying to send invalid packets, but rarely does this have any effect on the server.

**Comment by ADRFranklin** [comment]
As for the timing out issue, you would need to post more information about this, I have used SKY in all of my servers (that is 3 sa-mp servers) for the the last 4/5 years and I currently have no faced any issues with people timing out.

So please post more information about your setup, what configuration you have used, maybe a video or logs about the incident.

I will try to investigate the issue, but I can't promise to solve it if it's not related.

**Comment by elvianod982** [comment]
@realhus - the mass timing out is a known issue when using using Linux distributions such as CentOS 8, Debian 10, Ubuntu 18.04. Are you using one of those? If so, consider using CentOS 7 or Debian 8. Both of those are fine.

**Comment by realhus** [comment]
Yes im using ubuntu 18.04.3.

**Comment by ADRFranklin** [comment]
18.04.3 ships with Kernel 5, which is perfectly fine. It does not contain the broken networking that was with Kernel 4.9 - 4.18/19

Your timing out issue could be the result of your own code, if a function takes a long time to respond and it halts the script, players will timeout since no data will be sent back for them.

Every Server/Client has a timeout number set, which tells the client if you made this request and the host did not respond in x (x being the set timeout number) then drop the connection.

The reason for this, is to prevent the client/server infinitely waiting for a response from a client/host that may never respond, which would waste resources.

**Comment by realhus** [comment]
Mine doesnt come with kernel 5. 
Well. You can close this issue. Ill try to provide more details if the problem isnt solved
Thanks
